networks:
  mynetwork:
    external: true
    
services:
  youcast:
    image: node:22.19.0
    container_name: youcast
    networks:
      mynetwork:
        ipv4_address: 172.20.0.57
    ports:
      - "3456:3000"
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    environment:
      - NODE_ENV=development
    command: >
      bash -c "
        apt-get update &&
        apt-get install -y python3 python3-pip ffmpeg &&
        pip3 install --break-system-packages yt-dlp &&
        npm install --include=dev &&
        npm run dev
      "
    restart: unless-stopped
    stdin_open: true
    tty: true
